Repository SENG480a-NutriDine/mobile, pull requests merged in 2024-02, with the labels that each got.

#13 installed react native paper and ios builder
  app/app.json
  app/babel.config.js
  app/ios/.gitignore
  app/ios/.xcode.env
  app/ios/Podfile
  app/ios/Podfile.lock
  app/ios/Podfile.properties.json
  app/ios/mobile.xcodeproj/project.pbxproj
  app/ios/mobile.xcodeproj/xcshareddata/xcschemes/mobile.xcscheme
  app/ios/mobile.xcworkspace/contents.xcworkspacedata
  app/ios/mobile/AppDelegate.h
  app/ios/mobile/AppDelegate.mm
  app/ios/mobile/Images.xcassets/AppIcon.appiconset/App-Icon-1024x1024@1x.png
  app/ios/mobile/Images.xcassets/AppIcon.appiconset/Contents.json
  app/ios/mobile/Images.xcassets/Contents.json
  app/ios/mobile/Images.xcassets/SplashScreen.imageset/Contents.json
  app/ios/mobile/Images.xcassets/SplashScreen.imageset/image.png
  app/ios/mobile/Images.xcassets/SplashScreenBackground.imageset/Contents.json
  app/ios/mobile/Images.xcassets/SplashScreenBackground.imageset/image.png
  app/ios/mobile/Info.plist
  app/ios/mobile/SplashScreen.storyboard
  app/ios/mobile/Supporting/Expo.plist
  app/ios/mobile/main.m
  app/ios/mobile/mobile-Bridging-Header.h
  app/ios/mobile/mobile.entitlements
  app/ios/mobile/noop-file.swift
  app/package-lock.json
  app/package.json
Labels: task

#11 CI/CD Pipeline
  .github/workflows/ci.yml
  app/app.json
Labels: task

#16 Splash Screen
  app/App.tsx
  app/app.json
  app/assets/splash.png
  app/package-lock.json
  app/package.json
Labels: task

#17 Theme Configuration
  app/App.tsx
  app/app.json
  app/constants/styles/global.ts
  app/custom/ThemeCustomHook.ts
Labels: task

#26 Theme Config Fix
  app/App.tsx
  app/constants/styles/global.ts
  app/constants/styles/global.tsx
Labels: bug

#22 Routing & Food Form Setup
  app/app.json
  app/app/(tabs)/App.tsx
  app/app/(tabs)/DataSubmission.tsx
  app/app/(tabs)/_layout.tsx
  app/app/_layout.tsx
  app/app/index.tsx
  app/babel.config.js
  app/components/EnterFoodForm.tsx
  app/constants/styles/global.tsx
  app/package-lock.json
  app/package.json
Labels: task

#31 Food Entry Form
  app/app/(tabs)/DataSubmission.tsx
  app/app/(tabs)/_layout.tsx
  app/components/EnterFoodForm.tsx
  app/components/FormDropdown.tsx
  app/components/FormSwitch.tsx
  app/constants/objects/initializeFoodForm.ts
  app/constants/styles/global.tsx
  app/constants/types/types.ts
  app/custom/ThemeCustomHook.ts
  app/custom/functions/db/db.ts
  app/custom/functions/forms/formSubmission.ts
  app/custom/functions/forms/handleFormChanges.ts
  app/custom/hooks/ThemeCustomHook.ts
  app/custom/hooks/useMenu.ts
  app/custom/hooks/useRestaurants.ts
  app/package-lock.json
  app/package.json
Labels: task

#32 Remove expo-router/babel from babel.config.js file to fix build (hopefully)
  app/.gitignore
  app/babel.config.js
Labels: bug

#42 LoginUI and UserInfo Screen
  app/app/(tabs)/HomeScreen.tsx
  app/app/(tabs)/_layout.tsx
  app/app/(tabs)/userInfo.tsx
  app/app/App.tsx
  app/app/LoginScreen.tsx
  app/custom/userService.ts
  app/firebaseConfig.ts
  app/services/AuthService/AuthService.tsx
Labels: task, High priority
